# GoReleaser configuration for ignr
# See https://goreleaser.com for documentation

version: 2

project_name: ignr-cli

before:
  hooks:
    - go mod tidy

builds:
  - id: ignr
    main: ./cmd/ignr
    binary: ignr
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X go.seanlatimer.dev/ignr/pkg/cli.Version={{.Version}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: seanlatimer
    name: ignr-cli
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

homebrew_casks:
  - name: ignr
    repository:
      owner: seanlatimer
      name: homebrew-tap
    description: "Offline-first gitignore generator"
    homepage: "https://github.com/seanlatimer/ignr-cli"
    license: "MIT"
    binaries:
      - ignr
    commit_author:
      name: goreleaser
      email: goreleaser@users.noreply.github.com

scoops:
  - name: ignr
    repository:
      owner: seanlatimer
      name: scoop-bucket
    description: "Offline-first gitignore generator"
    homepage: "https://github.com/seanlatimer/ignr-cli"
    license: "MIT"
    commit_author:
      name: goreleaser
      email: goreleaser@users.noreply.github.com
