package templates

import (
	"strings"
	"time"
)

type MergeOptions struct {
	Deduplicate bool
	AddHeader   bool
	Generator   string
	Version     string
	Timestamp   time.Time
}

func MergeTemplates(loaded []LoadedTemplate, opts MergeOptions) string {
	var builder strings.Builder

	if opts.AddHeader {
		header := BuildHeader(loaded, opts.Generator, opts.Version, opts.Timestamp)
		builder.WriteString(header)
	}

	for i, t := range loaded {
		if i > 0 {
			builder.WriteString("\n\n")
		}
		builder.WriteString("# --- ")
		builder.WriteString(t.Template.Name)
		builder.WriteString(" ---\n")
		builder.WriteString(strings.TrimRight(t.Content, "\n"))
		builder.WriteString("\n")
	}

	merged := builder.String()
	if !opts.Deduplicate {
		return merged
	}

	return DeduplicateLines(merged)
}

func DeduplicateLines(content string) string {
	lines := strings.Split(content, "\n")
	seen := make(map[string]struct{}, len(lines))
	out := make([]string, 0, len(lines))

	for _, line := range lines {
		if _, ok := seen[line]; ok {
			continue
		}
		seen[line] = struct{}{}
		out = append(out, line)
	}

	return strings.Join(out, "\n")
}

func BuildHeader(loaded []LoadedTemplate, generator, version string, timestamp time.Time) string {
	if timestamp.IsZero() {
		timestamp = time.Now()
	}

	templateNames := make([]string, 0, len(loaded))
	for _, t := range loaded {
		templateNames = append(templateNames, t.Template.Name)
	}

	var builder strings.Builder
	builder.WriteString("# Generated by ")
	builder.WriteString(generator)
	if version != "" {
		builder.WriteString(" ")
		builder.WriteString(version)
	}
	builder.WriteString("\n")
	builder.WriteString("# Timestamp: ")
	builder.WriteString(timestamp.Format(time.RFC3339))
	builder.WriteString("\n")
	builder.WriteString("# Templates: ")
	builder.WriteString(strings.Join(templateNames, ", "))
	builder.WriteString("\n\n")

	return builder.String()
}
